AWSTemplateFormatVersion: "2010-09-09"
#TODO - Security Groups
#TODO - Instance Role
#TODO - Automate HammerDB configuration
#TODO - Output Parameters
#TODO - Input Parameters (VPC, Subnet, DB Configuration)
Resources:
  DBMonitoringRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: 'Role to add monitoring to RDS instance'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "monitoring.rds.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  HammerDBTestDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'HammerDBTestDB'
      DBName: 'HammerDBTestDB'
      DBInstanceClass: 'db.m5.large'
      AllocatedStorage: 100
      Iops: 1000
      Engine: 'postgres'
      EngineVersion: '12.5'
      MasterUsername: 'awsuser'
      MasterUserPassword: 'AwsUser123!'
      EnablePerformanceInsights: 'True'
      MonitoringInterval: '30'
      MonitoringRoleArn: !GetAtt DBMonitoringRole.Arn
  HammerDBInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cf6f5c8a62fa5da6
      KeyName: key_generic.pem
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "false"
            VolumeSize: "20"
      Tags:
        - Key: Environment
          Value: hammerdb
        - Key: Name
          Value: hammerdb-instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            yum -y update
            echo "1. Downloading HammerDB Tar"
            cd /home/ec2-user
            curl -L https://github.com/TPC-Council/HammerDB/releases/download/v4.1/HammerDB-4.1-Linux.tar.gz >> HammerDB-4.1-Linux.tar.gz
            tar -zxvf HammerDB-4.1-Linux.tar.gz

            echo "2. Install postgreSQL client"
            tee /etc/yum.repos.d/pgdg.repo<<EOF
            [pgdg12]
            name=PostgreSQL 12 for RHEL/CentOS 7 - x86_64
            baseurl=https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-7-x86_64
            enabled=1
            gpgcheck=0
            EOF
            yum makecache


